# -*- coding: utf-8 -*-
"""Analisis de Sentimiento.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vzncwbd1U_503_8jRu_foMAfh10NltPh
"""

from transformers import pipeline

clasificacion_1 = pipeline('sentiment-analysis')

clasificacion_1('This image is horrible')

clasificacion_2 = pipeline('sentiment-analysis', model='finiteautomata/beto-sentiment-analysis')

clasificacion_2(
    [
        'Que hermoso dia',
        'Que producto tan malo',
        'Hace calor',
        'Ya inicia el invierno'
    ]
)

ner_1 = pipeline('ner')
ner_1('My name is Yersel and I work in Warner Bros park')

ner_2 = pipeline('ner', grouped_entities=True)
ner_2('My name is Juan and I work in the Warner Bros Park')

ner_3 = pipeline('ner', grouped_entities=True, model='Babelscape/wikineural-multilingual-ner')
ner_3('Mi nombre es Pedro y trabajo en el parque Warner Bros. Soy de Peru')

